/**
 * Edge Cache Strategy
 * Sets Cache-Control, Surrogate-Control, and CDN-Cache-Control headers
 * for Cloudflare / Fly.io edge nodes.
 *
 * Rules:
 *   Static assets   → public, 1 year, immutable  (hashed filenames from Vite)
 *   API health       → no-store
 *   API read-only    → private, 30s stale-while-revalidate
 *   API mutations    → no-store
 *   HTML shell       → no-cache (revalidate every request)
 */

export type CacheProfile =
  | "static-immutable"   // /assets/* (hashed)
  | "html-shell"         // index.html
  | "api-public-read"    // /api/health, /api/items (public data)
  | "api-private-read"   // authenticated reads (user-specific)
  | "api-mutation"       // POST/PUT/DELETE
  | "no-store";          // sensitive / real-time

const PROFILES: Record<CacheProfile, string> = {
  "static-immutable": "public, max-age=31536000, immutable",
  "html-shell":       "public, max-age=0, must-revalidate",
  "api-public-read":  "public, max-age=30, stale-while-revalidate=60",
  "api-private-read": "private, max-age=10, stale-while-revalidate=20",
  "api-mutation":     "no-store",
  "no-store":         "no-store, no-cache, private",
};

// Same headers targeted at CDN layers (Cloudflare CDN-Cache-Control)
const CDN_PROFILES: Record<CacheProfile, string | null> = {
  "static-immutable": "public, max-age=31536000, immutable",
  "html-shell":       "no-store",    // never cache HTML at edge
  "api-public-read":  "public, max-age=30, stale-while-revalidate=120",
  "api-private-read": null,          // do not cache private at edge
  "api-mutation":     null,
  "no-store":         null,
};

export function getCacheHeaders(profile: CacheProfile): Record<string, string> {
  const headers: Record<string, string> = {
    "Cache-Control": PROFILES[profile],
  };
  const cdn = CDN_PROFILES[profile];
  if (cdn) {
    headers["CDN-Cache-Control"]       = cdn; // Cloudflare CDN-only
    headers["Surrogate-Control"]       = cdn; // Varnish / Fly edge
  }
  return headers;
}

/** Express middleware: auto-selects cache profile based on request path + method */
export function edgeCacheMiddleware(req: any, res: any, next: () => void): void {
  const { method, path } = req;

  let profile: CacheProfile = "no-store";

  if (path.startsWith("/assets/") || path.match(/\.(js|css|woff2?|ttf|eot|svg|png|jpg|webp|ico)(\?.*)?$/)) {
    profile = "static-immutable";
  } else if (path === "/" || path === "/index.html") {
    profile = "html-shell";
  } else if (path.startsWith("/api/")) {
    if (method !== "GET" && method !== "HEAD") {
      profile = "api-mutation";
    } else if (
      path === "/api/health" ||
      path.startsWith("/api/items") ||
      path.startsWith("/api/branding")
    ) {
      profile = "api-public-read";
    } else {
      profile = "api-private-read";
    }
  }

  const headers = getCacheHeaders(profile);
  for (const [k, v] of Object.entries(headers)) {
    res.setHeader(k, v);
  }

  next();
}

/**
 * Returns Cloudflare _headers file content for static deployments.
 * Write this to public/_headers if using Cloudflare Pages.
 */
export function generateCloudflareHeadersFile(): string {
  return `# Auto-generated by edge-cache.ts — do not edit manually
# https://developers.cloudflare.com/pages/configuration/headers/

/assets/*
  Cache-Control: public, max-age=31536000, immutable
  CDN-Cache-Control: public, max-age=31536000, immutable

/
  Cache-Control: public, max-age=0, must-revalidate
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(self), geolocation=()
  Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; media-src 'self' blob:; connect-src 'self' wss:

/*.html
  Cache-Control: public, max-age=0, must-revalidate

/api/*
  Cache-Control: no-store
`;
}
