/**
 * Cambridge Exam Framework
 *
 * Single source of truth for all Cambridge Young Learners (YLE) and
 * Cambridge English Qualifications knowledge embedded in the AI engine.
 *
 * Covers:
 *  - Cambridge YLE Starters (Pre-A1)
 *  - Cambridge YLE Movers   (A1)
 *  - Cambridge YLE Flyers   (A2)
 *  - Cambridge A2 Key        (KET)
 *  - Cambridge B1 Preliminary (PET)
 *
 * Sources:
 *  - Cambridge Assessment English — official exam handbooks & syllabuses (2024)
 *  - Cambridge English Young Learners: Handbook for Teachers
 *  - Cambridge Assessment English: A2 Key Handbook for Teachers
 *  - Cambridge Assessment English: B1 Preliminary Handbook for Teachers
 *  - CEFR Companion Volume (Council of Europe, 2020)
 *  - Cambridge Word Lists (official vocabulary lists per exam)
 */

import type { CefrLevel } from "../assessment-engine/types";

// ─────────────────────────────────────────────────────────────────────────────
// 1. EXAM IDENTIFIERS
// ─────────────────────────────────────────────────────────────────────────────

export type CambridgeExam =
  | "STARTERS" // YLE Pre-A1
  | "MOVERS"   // YLE A1
  | "FLYERS"   // YLE A2
  | "KET"      // A2 Key (formerly Key English Test)
  | "PET";     // B1 Preliminary (formerly Preliminary English Test)

export type CambridgeSkill =
  | "READING_WRITING" // YLE combines reading & writing
  | "READING"
  | "WRITING"
  | "LISTENING"
  | "SPEAKING";

// ─────────────────────────────────────────────────────────────────────────────
// 2. TASK TYPE TAXONOMY
// ─────────────────────────────────────────────────────────────────────────────

export type CambridgeItemFormat =
  | "PICTURE_MATCHING"          // Match word/sentence to picture
  | "CATEGORISATION"            // Tick correct category / column
  | "SENTENCE_COMPLETION"       // Complete sentence from word bank
  | "CLOZE_MCQ"                 // Multiple-choice cloze (3–4 options)
  | "CLOZE_OPEN"                // Open cloze (no options given)
  | "WORD_FORM"                 // Word-formation cloze
  | "READING_MCQ"               // Read text, answer 3-option MCQ
  | "READING_GAPPED_TEXT"       // Sentences/paragraphs removed from text
  | "READING_MATCHING"          // Match people/headings to texts
  | "SHORT_MESSAGE"             // Write short email/message (~100 words)
  | "ARTICLE_OR_STORY"          // Write article/story (~100 words)
  | "DRAWING_LINES"             // Listening: match name to picture (YLE)
  | "PICTURE_DIALOGUE_MCQ"      // Listening: 3-picture MCQ
  | "GAP_FILL_LISTEN"           // Listening: complete notes/form
  | "MATCHING_LISTEN"           // Listening: match descriptions to options
  | "SPOT_DIFFERENCES"          // Speaking: find differences in two pictures
  | "DESCRIBE_PHOTO"            // Speaking: describe/talk about a photo
  | "COLLABORATIVE_TASK"        // Speaking: discuss and decide together
  | "PERSONAL_QUESTIONS"        // Speaking: answer questions about yourself
  | "STORY_SEQUENCING"          // Speaking YLE: sequence picture cards, tell story
  | "COLOURING_WRITING";        // Listening YLE: colour and write

export interface CambridgeTask {
  /** Unique identifier, e.g. "STARTERS_R_PART1" */
  id: string;
  exam: CambridgeExam;
  skill: CambridgeSkill;
  partNumber: number;
  name: string;
  format: CambridgeItemFormat;
  /** Number of scorable items in this part */
  itemCount: number;
  /** Marks per correct item */
  marksPerItem: number;
  /** Target CEFR level for items in this part */
  cefr: CefrLevel;
  /** Word count range for stimulus text (where applicable) */
  stimulusWordRange?: [number, number];
  /** Word count target for productive tasks (writing) */
  outputWordTarget?: [number, number];
  /** Number of answer options (MCQ only) */
  optionCount?: number;
  /** Description of what the candidate must do */
  candidateTask: string;
  /** Description of stimulus material */
  stimulusDescription: string;
  /** Distractor guidance for AI generation */
  distractorGuidance: string;
  /** Vocabulary / grammar constraints */
  languageConstraints: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// 3. FULL TASK INVENTORY
// ─────────────────────────────────────────────────────────────────────────────

export const CAMBRIDGE_TASKS: CambridgeTask[] = [
  // ── STARTERS ─────────────────────────────────────────────────────────────
  {
    id: "STARTERS_RW_PART1",
    exam: "STARTERS",
    skill: "READING_WRITING",
    partNumber: 1,
    name: "Starters R&W Part 1 — Word–Picture Matching",
    format: "PICTURE_MATCHING",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "PRE_A1",
    candidateTask: "Look at the five pictures. Read the three-word labels. Draw lines to match each label to the correct picture.",
    stimulusDescription: "Five simple colour illustrations of concrete nouns (animals, food, toys, classroom objects, body parts).",
    distractorGuidance: "Wrong labels must come from the same semantic category (e.g., all animals) so the distractor is plausible but clearly wrong when matched to the picture.",
    languageConstraints: "Single-word nouns or simple noun phrases only. From the official Cambridge Starters Word List (~150 words). Avoid irregular spellings not yet encountered.",
  },
  {
    id: "STARTERS_RW_PART2",
    exam: "STARTERS",
    skill: "READING_WRITING",
    partNumber: 2,
    name: "Starters R&W Part 2 — Read and Tick Correct Box",
    format: "CATEGORISATION",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "PRE_A1",
    candidateTask: "Read the sentence. Tick (✓) the box for 'yes' or 'no'. All sentences are about a picture shown.",
    stimulusDescription: "One scene picture (e.g., a bedroom, a park) with 5 descriptive sentences to verify.",
    distractorGuidance: "Incorrect sentences should change one key element (colour, number, location) so they look plausible. Avoid obviously impossible statements.",
    languageConstraints: "Simple present tense. Sentences under 10 words. Subject + verb + object/adjective only. Starters vocabulary only.",
  },
  {
    id: "STARTERS_RW_PART3",
    exam: "STARTERS",
    skill: "READING_WRITING",
    partNumber: 3,
    name: "Starters R&W Part 3 — Read and Write",
    format: "SENTENCE_COMPLETION",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "PRE_A1",
    stimulusWordRange: [4, 8],
    candidateTask: "Read the question. Look at the picture. Write one word to complete the answer.",
    stimulusDescription: "A simple scene picture with 5 question-answer pairs (Q: What colour is the ball? A: The ball is ___.).",
    distractorGuidance: "Correct answer is a single visible word from the picture. Wrong answers are plausible but contradicted by the image.",
    languageConstraints: "One-word answers only (colour, number, adjective, or simple noun). Starters vocabulary.",
  },
  {
    id: "STARTERS_RW_PART4",
    exam: "STARTERS",
    skill: "READING_WRITING",
    partNumber: 4,
    name: "Starters R&W Part 4 — Read and Circle",
    format: "CLOZE_MCQ",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "PRE_A1",
    stimulusWordRange: [5, 10],
    optionCount: 3,
    candidateTask: "Read each sentence. Choose the correct word (circle A, B, or C).",
    stimulusDescription: "Five stand-alone sentences, each with a 3-option lexical or structural gap.",
    distractorGuidance: "Distractors must be the same word class (all nouns / all verbs). Do not use words outside the Starters word list as options.",
    languageConstraints: "Simple present or simple past only. Sentences ≤10 words. All vocabulary from Starters Word List.",
  },
  {
    id: "STARTERS_RW_PART5",
    exam: "STARTERS",
    skill: "READING_WRITING",
    partNumber: 5,
    name: "Starters R&W Part 5 — Look and Write",
    format: "PICTURE_MATCHING",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "PRE_A1",
    candidateTask: "Look at the picture. Write the missing word to complete the sentence below each picture.",
    stimulusDescription: "Five separate pictures, each accompanied by an incomplete sentence directly describing the picture.",
    distractorGuidance: "Answer word is unambiguously shown in the picture. Confirm there is no other plausible interpretation.",
    languageConstraints: "Single-word fill-in from Starters vocabulary. CVC or CCVC word patterns preferred.",
  },
  {
    id: "STARTERS_L_PART1",
    exam: "STARTERS",
    skill: "LISTENING",
    partNumber: 1,
    name: "Starters Listening Part 1 — Drawing Lines",
    format: "DRAWING_LINES",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "PRE_A1",
    candidateTask: "Listen to the conversation. Draw a line from the name to the correct person in the picture.",
    stimulusDescription: "Scene picture with several people. Names are read aloud, candidates draw lines to identify them.",
    distractorGuidance: "Names must be clearly different phonetically. Each person has a distinct visual feature mentioned in the dialogue.",
    languageConstraints: "Common English first names. Physical descriptors: tall/short, wearing [colour] [garment], holding [object]. Starters vocabulary.",
  },
  {
    id: "STARTERS_L_PART2",
    exam: "STARTERS",
    skill: "LISTENING",
    partNumber: 2,
    name: "Starters Listening Part 2 — Write Names / Numbers",
    format: "GAP_FILL_LISTEN",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "PRE_A1",
    candidateTask: "Listen and write the name or number you hear.",
    stimulusDescription: "Short dialogue. Speaker spells out names or states small numbers. Candidates write what they hear.",
    distractorGuidance: "Names should be spelled out in the audio (e.g., 'M-A-X'). Numbers up to 20 only.",
    languageConstraints: "Numbers 1–20, common names, simple spellings. No abbreviations.",
  },
  {
    id: "STARTERS_L_PART3",
    exam: "STARTERS",
    skill: "LISTENING",
    partNumber: 3,
    name: "Starters Listening Part 3 — Tick the Box",
    format: "PICTURE_DIALOGUE_MCQ",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "PRE_A1",
    optionCount: 3,
    candidateTask: "Listen. What does [name] like? Tick the box under the correct picture (A, B, or C).",
    stimulusDescription: "Three-picture strip per question. A short dialogue establishes preference or fact. Candidates tick the matching picture.",
    distractorGuidance: "Distractors must be plausible: they are mentioned in the dialogue or are semantically similar. Correct answer confirmed by clear positive statement in audio.",
    languageConstraints: "Like / don't like / has / doesn't have. Starters vocabulary only.",
  },
  {
    id: "STARTERS_L_PART4",
    exam: "STARTERS",
    skill: "LISTENING",
    partNumber: 4,
    name: "Starters Listening Part 4 — Tick or Cross",
    format: "CATEGORISATION",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "PRE_A1",
    candidateTask: "Listen. Is this right (✓) or wrong (✗)?",
    stimulusDescription: "Short statements or simple exchanges about a picture. Candidate validates each statement.",
    distractorGuidance: "Avoid ambiguous statements. Correct/incorrect must be clearly determinable from the audio.",
    languageConstraints: "Simple present. Starters vocabulary.",
  },
  {
    id: "STARTERS_L_PART5",
    exam: "STARTERS",
    skill: "LISTENING",
    partNumber: 5,
    name: "Starters Listening Part 5 — Colour and Write",
    format: "COLOURING_WRITING",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "PRE_A1",
    candidateTask: "Listen to the instructions. Colour the picture and write the word.",
    stimulusDescription: "Line drawing. Audio tells the candidate to colour specific parts and write one word in a box.",
    distractorGuidance: "Colour names must be distinct. Writing task requires only one clearly dictated word.",
    languageConstraints: "Colour vocabulary, basic object nouns, prepositional phrases (next to, on top of). Starters vocabulary.",
  },
  {
    id: "STARTERS_S_PART1",
    exam: "STARTERS",
    skill: "SPEAKING",
    partNumber: 1,
    name: "Starters Speaking Part 1 — Point to the Picture",
    format: "PERSONAL_QUESTIONS",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "PRE_A1",
    candidateTask: "The examiner shows a large scene picture. Candidate points to named objects/people.",
    stimulusDescription: "Colourful scene card with many objects, people, and animals.",
    distractorGuidance: "Instructions combine two attributes (e.g., 'the red ball next to the tree') so pointing requires processing two pieces of information.",
    languageConstraints: "Receptive only — candidate follows instructions, no production required. Starters vocabulary.",
  },
  {
    id: "STARTERS_S_PART2",
    exam: "STARTERS",
    skill: "SPEAKING",
    partNumber: 2,
    name: "Starters Speaking Part 2 — Find the Differences",
    format: "PERSONAL_QUESTIONS",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "PRE_A1",
    candidateTask: "Examiner says 'In my picture the [object] is [colour/action]. What about your picture?' Candidate describes difference.",
    stimulusDescription: "Two similar scene cards with five differences. Each candidate and examiner holds one.",
    distractorGuidance: "Differences should involve a change in colour, number, or position — not require complex description.",
    languageConstraints: "In my picture the [noun] is [adj]. Starters vocabulary.",
  },
  {
    id: "STARTERS_S_PART3",
    exam: "STARTERS",
    skill: "SPEAKING",
    partNumber: 3,
    name: "Starters Speaking Part 3 — Personal Questions",
    format: "PERSONAL_QUESTIONS",
    itemCount: 4,
    marksPerItem: 1,
    cefr: "PRE_A1",
    candidateTask: "Answer simple personal questions (name, age, where you live, hobbies).",
    stimulusDescription: "No visual stimulus. Examiner asks 4 personal questions.",
    distractorGuidance: "N/A — production task. Questions must be answerable with 1–3 words.",
    languageConstraints: "What's your name? How old are you? Where do you live? Do you like [X]? Starters vocabulary.",
  },

  // ── MOVERS ───────────────────────────────────────────────────────────────
  {
    id: "MOVERS_RW_PART1",
    exam: "MOVERS",
    skill: "READING_WRITING",
    partNumber: 1,
    name: "Movers R&W Part 1 — Matching Definitions",
    format: "PICTURE_MATCHING",
    itemCount: 6,
    marksPerItem: 1,
    cefr: "A1",
    stimulusWordRange: [8, 15],
    optionCount: 8,
    candidateTask: "Read the definition. Choose the correct word from the box (8 options, 6 used).",
    stimulusDescription: "Six one-sentence definitions. Word box of 8 candidate words (2 distractors).",
    distractorGuidance: "Distractors in the word box must be the same word class as correct answers. Extra distractors are plausible but clearly don't match any definition.",
    languageConstraints: "All vocabulary from Movers Word List (~300 words). Definitions use only Starters/Movers vocabulary.",
  },
  {
    id: "MOVERS_RW_PART2",
    exam: "MOVERS",
    skill: "READING_WRITING",
    partNumber: 2,
    name: "Movers R&W Part 2 — Multiple-Choice Cloze Dialogue",
    format: "CLOZE_MCQ",
    itemCount: 6,
    marksPerItem: 1,
    cefr: "A1",
    stimulusWordRange: [60, 100],
    optionCount: 3,
    candidateTask: "Read the conversation. Choose the correct word (A, B, or C) to complete each gap.",
    stimulusDescription: "Short dialogue (6–8 turns) with 6 lexical or grammatical gaps.",
    distractorGuidance: "Distractors must be same word class. At least one distractor should be phonologically similar to the correct answer to test discrimination.",
    languageConstraints: "Movers vocabulary. Simple present, simple past, present continuous. Avoid complex subordinate clauses.",
  },
  {
    id: "MOVERS_RW_PART3",
    exam: "MOVERS",
    skill: "READING_WRITING",
    partNumber: 3,
    name: "Movers R&W Part 3 — Read and Choose",
    format: "READING_MCQ",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "A1",
    stimulusWordRange: [100, 150],
    optionCount: 3,
    candidateTask: "Read the text. Choose the best answer (A, B, or C) for each question.",
    stimulusDescription: "Short continuous text (story or description). 5 comprehension questions follow.",
    distractorGuidance: "Distractors must be partially supported by the text but not fully correct — avoid answers that require inference beyond the text.",
    languageConstraints: "Movers topics: home, school, sport, food, animals, weather. Simple past/present. Direct and indirect information retrieval tasks.",
  },
  {
    id: "MOVERS_RW_PART4",
    exam: "MOVERS",
    skill: "READING_WRITING",
    partNumber: 4,
    name: "Movers R&W Part 4 — Read and Write",
    format: "SENTENCE_COMPLETION",
    itemCount: 7,
    marksPerItem: 1,
    cefr: "A1",
    stimulusWordRange: [100, 150],
    candidateTask: "Read the text. Fill in the gaps with one word each.",
    stimulusDescription: "Descriptive or narrative text with 7 single-word gaps. No options given.",
    distractorGuidance: "Each gap has exactly one plausible correct answer. Surrounding context must constrain the answer to one word.",
    languageConstraints: "Articles, prepositions, simple verbs, Movers vocabulary. Answers are single words.",
  },
  {
    id: "MOVERS_RW_PART5",
    exam: "MOVERS",
    skill: "READING_WRITING",
    partNumber: 5,
    name: "Movers R&W Part 5 — Gapped Story",
    format: "CLOZE_MCQ",
    itemCount: 6,
    marksPerItem: 1,
    cefr: "A1",
    stimulusWordRange: [80, 120],
    optionCount: 3,
    candidateTask: "Read the story. Choose the correct word (A, B, or C) to fill each gap.",
    stimulusDescription: "Short narrative story with 6 gaps, each offering 3 options.",
    distractorGuidance: "All three options must make grammatical sense. Semantic plausibility distinguishes correct from wrong. Test grammar (verb form, tense) or vocabulary.",
    languageConstraints: "Past simple, past continuous. Movers narrative vocabulary. Cohesive devices (then, next, after that).",
  },
  {
    id: "MOVERS_RW_PART6",
    exam: "MOVERS",
    skill: "READING_WRITING",
    partNumber: 6,
    name: "Movers R&W Part 6 — Look and Write",
    format: "SENTENCE_COMPLETION",
    itemCount: 6,
    marksPerItem: 1,
    cefr: "A1",
    candidateTask: "Look at the picture. Write the missing word to complete each sentence about the picture.",
    stimulusDescription: "Detailed scene picture. Six incomplete sentences describe specific elements visible in the picture.",
    distractorGuidance: "Each answer is visually unambiguous. Candidate must read the sentence carefully and extract the correct word from the image.",
    languageConstraints: "Single-word answers: colour adjectives, number words, object nouns, action verbs (present continuous). Movers vocabulary.",
  },
  {
    id: "MOVERS_L_PART1",
    exam: "MOVERS",
    skill: "LISTENING",
    partNumber: 1,
    name: "Movers Listening Part 1 — Drawing Lines",
    format: "DRAWING_LINES",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "A1",
    candidateTask: "Listen to the conversation. Draw a line from the name to the correct person.",
    stimulusDescription: "Busy scene picture with 6–8 people. 5 names on the side.",
    distractorGuidance: "Physical descriptions must be detailed enough to uniquely identify the person (two distinguishing features per person).",
    languageConstraints: "She's/He's got [hair type]. She's/He's wearing [clothing + colour]. Physical description vocabulary. Movers vocabulary.",
  },
  {
    id: "MOVERS_L_PART2",
    exam: "MOVERS",
    skill: "LISTENING",
    partNumber: 2,
    name: "Movers Listening Part 2 — Write Information",
    format: "GAP_FILL_LISTEN",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "A1",
    candidateTask: "Listen to the conversation. Write the missing information in the form/table.",
    stimulusDescription: "A form, chart, or list with 5 blank fields (name, day, time, price, number).",
    distractorGuidance: "Audio should confirm the answer, then potentially offer a near-distractor (e.g., 'No, not Thursday — Friday').",
    languageConstraints: "Days, numbers, times, simple nouns. Movers vocabulary. Information given once with one confirmation.",
  },
  {
    id: "MOVERS_L_PART3",
    exam: "MOVERS",
    skill: "LISTENING",
    partNumber: 3,
    name: "Movers Listening Part 3 — Match the Pictures",
    format: "MATCHING_LISTEN",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "A1",
    optionCount: 8,
    candidateTask: "Listen. Write a letter (A–H) next to each name to match the person to the activity/object.",
    stimulusDescription: "8 picture options (A–H). 5 names. Audio dialogue describes each person's preference.",
    distractorGuidance: "All 8 pictures must be mentioned or alluded to in the audio. Only 5 are used; 3 are distractors.",
    languageConstraints: "Would like / likes / is going to. Activities and hobbies vocabulary. Movers vocabulary.",
  },
  {
    id: "MOVERS_L_PART4",
    exam: "MOVERS",
    skill: "LISTENING",
    partNumber: 4,
    name: "Movers Listening Part 4 — Tick the Box",
    format: "PICTURE_DIALOGUE_MCQ",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "A1",
    optionCount: 3,
    candidateTask: "Listen to the conversation. Look at the three pictures. Tick (✓) the correct answer.",
    stimulusDescription: "Five questions, each with three pictures. Short dialogue determines the correct picture.",
    distractorGuidance: "Distractors are plausible: items mentioned but not selected; items from same semantic field as answer.",
    languageConstraints: "Questions about preferences, locations, descriptions. Movers vocabulary. Avoid complex conditionals.",
  },
  {
    id: "MOVERS_L_PART5",
    exam: "MOVERS",
    skill: "LISTENING",
    partNumber: 5,
    name: "Movers Listening Part 5 — Colour and Write",
    format: "COLOURING_WRITING",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "A1",
    candidateTask: "Listen to the instructions. Colour the objects and write a word.",
    stimulusDescription: "Uncoloured line drawing with several objects to colour and one space to write a word.",
    distractorGuidance: "Colour and position described clearly. Writing task: one concrete noun spelled out or phonetically clear.",
    languageConstraints: "Colour names, prepositional phrases (between, behind, in front of), single nouns. Movers vocabulary.",
  },
  {
    id: "MOVERS_S_PART1",
    exam: "MOVERS",
    skill: "SPEAKING",
    partNumber: 1,
    name: "Movers Speaking Part 1 — Spot the Differences",
    format: "SPOT_DIFFERENCES",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "A1",
    candidateTask: "Tell the examiner what is different in your picture compared to theirs.",
    stimulusDescription: "Two similar pictures. Five differences involving colour, number, object, or action.",
    distractorGuidance: "Differences should require production of adjectives, colours, and simple prepositional phrases.",
    languageConstraints: "In my picture the [noun] is [adj/colour]. There is/are [number] [noun]. Movers vocabulary.",
  },
  {
    id: "MOVERS_S_PART2",
    exam: "MOVERS",
    skill: "SPEAKING",
    partNumber: 2,
    name: "Movers Speaking Part 2 — Personal Questions",
    format: "PERSONAL_QUESTIONS",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "A1",
    candidateTask: "Answer questions about yourself (school, family, hobbies, likes/dislikes).",
    stimulusDescription: "No visual. Examiner asks 5 personal questions.",
    distractorGuidance: "N/A — production. Questions should elicit 1–3 sentence answers.",
    languageConstraints: "Simple present, going to + future. Questions: What do you like/do/have? Tell me about your [X]. Movers vocabulary.",
  },

  // ── FLYERS ───────────────────────────────────────────────────────────────
  {
    id: "FLYERS_RW_PART1",
    exam: "FLYERS",
    skill: "READING_WRITING",
    partNumber: 1,
    name: "Flyers R&W Part 1 — Definition Matching",
    format: "PICTURE_MATCHING",
    itemCount: 10,
    marksPerItem: 1,
    cefr: "A2",
    stimulusWordRange: [10, 20],
    optionCount: 15,
    candidateTask: "Read the definition. Find the correct word in the box (15 options, 10 used).",
    stimulusDescription: "Ten sentence-level definitions. Word box with 15 options (5 distractors). Multi-word expressions included.",
    distractorGuidance: "Distractors must be same word class. At least 2 distractors should look or sound like a correct answer.",
    languageConstraints: "Flyers vocabulary (~500 words). Definitions use relative clauses. Multi-word phrases allowed (e.g., 'an old building where…').",
  },
  {
    id: "FLYERS_RW_PART2",
    exam: "FLYERS",
    skill: "READING_WRITING",
    partNumber: 2,
    name: "Flyers R&W Part 2 — Multiple-Choice Text",
    format: "READING_MCQ",
    itemCount: 6,
    marksPerItem: 1,
    cefr: "A2",
    stimulusWordRange: [100, 200],
    optionCount: 3,
    candidateTask: "Read the text. Choose the correct word (A, B, or C) for each gap.",
    stimulusDescription: "Continuous text (magazine article, letter, or description) with 6 lexical or grammatical gaps.",
    distractorGuidance: "Target lexical items at A2 boundary (phrasal verbs, collocations). Grammatical distractors test tense and agreement.",
    languageConstraints: "Present perfect, comparatives/superlatives, modal verbs. Flyers vocabulary.",
  },
  {
    id: "FLYERS_RW_PART3",
    exam: "FLYERS",
    skill: "READING_WRITING",
    partNumber: 3,
    name: "Flyers R&W Part 3 — Read and Choose",
    format: "READING_MCQ",
    itemCount: 10,
    marksPerItem: 1,
    cefr: "A2",
    stimulusWordRange: [200, 300],
    optionCount: 3,
    candidateTask: "Read the story. Choose the best answer for each question.",
    stimulusDescription: "Narrative or factual text (approx. 250 words). 10 comprehension questions.",
    distractorGuidance: "Include inference questions (why / how / what does X mean) alongside literal retrieval questions. Distractors use different wording for same idea.",
    languageConstraints: "Mix of direct retrieval (scanning) and inference tasks. Flyers vocabulary and grammar.",
  },
  {
    id: "FLYERS_RW_PART4",
    exam: "FLYERS",
    skill: "READING_WRITING",
    partNumber: 4,
    name: "Flyers R&W Part 4 — Gapped Text",
    format: "READING_GAPPED_TEXT",
    itemCount: 10,
    marksPerItem: 1,
    cefr: "A2",
    stimulusWordRange: [150, 250],
    candidateTask: "Read the text. Fill in the gaps with one word each (no options).",
    stimulusDescription: "Informational or descriptive passage with 10 single-word open gaps.",
    distractorGuidance: "Each gap tests a specific grammar point (article, preposition, auxiliary) or vocabulary item. Context must be sufficient to determine the unique correct answer.",
    languageConstraints: "Articles, prepositions, auxiliary verbs, pronouns, and basic content words. Flyers vocabulary.",
  },
  {
    id: "FLYERS_RW_PART5",
    exam: "FLYERS",
    skill: "READING_WRITING",
    partNumber: 5,
    name: "Flyers R&W Part 5 — Read and Answer",
    format: "SENTENCE_COMPLETION",
    itemCount: 7,
    marksPerItem: 1,
    cefr: "A2",
    stimulusWordRange: [200, 300],
    candidateTask: "Read the text. Write short answers to the questions using words from the text.",
    stimulusDescription: "Factual text. 7 questions require short-answer responses (1–5 words).",
    distractorGuidance: "Questions require locating and rephrasing specific information. Avoid questions answerable without reading the text.",
    languageConstraints: "Answers 1–5 words. Exact or near-paraphrase of text. Flyers vocabulary.",
  },
  {
    id: "FLYERS_RW_PART6",
    exam: "FLYERS",
    skill: "READING_WRITING",
    partNumber: 6,
    name: "Flyers R&W Part 6 — Guided Writing",
    format: "SHORT_MESSAGE",
    itemCount: 1,
    marksPerItem: 5,
    cefr: "A2",
    outputWordTarget: [40, 60],
    candidateTask: "Look at the three pictures. Write a story in about 50 words.",
    stimulusDescription: "Three sequential pictures that form a short narrative. Candidate writes a short story to accompany them.",
    distractorGuidance: "N/A — productive writing task. Mark scheme assesses: task completion (3 points), language accuracy (1 pt), range (1 pt).",
    languageConstraints: "Past tense narrative. Connect the three pictures coherently. Flyers vocabulary. At least 3 sentences.",
  },
  {
    id: "FLYERS_L_PART1",
    exam: "FLYERS",
    skill: "LISTENING",
    partNumber: 1,
    name: "Flyers Listening Part 1 — Drawing Lines",
    format: "DRAWING_LINES",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "A2",
    candidateTask: "Listen and draw lines to match names to people in the picture.",
    stimulusDescription: "A more complex scene with 8 people. 5 are named in audio.",
    distractorGuidance: "Descriptions include relative clauses and compound descriptions. Two plausible people per item to distinguish.",
    languageConstraints: "Who's/which person is [description]? Relative clauses. Present perfect for recent actions. Flyers vocabulary.",
  },
  {
    id: "FLYERS_L_PART2",
    exam: "FLYERS",
    skill: "LISTENING",
    partNumber: 2,
    name: "Flyers Listening Part 2 — Write Numbers/Words",
    format: "GAP_FILL_LISTEN",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "A2",
    candidateTask: "Listen to the conversation. Write the missing information (number, day, or word).",
    stimulusDescription: "A longer dialogue (~100 words). 5 gaps in a printed form/table.",
    distractorGuidance: "Audio should provide a self-correction for at least 2 items (e.g., 'I thought it was £15 but it's £50'). Candidates must track corrections.",
    languageConstraints: "Numbers up to 1000, times, dates, compound nouns. Flyers vocabulary.",
  },
  {
    id: "FLYERS_L_PART3",
    exam: "FLYERS",
    skill: "LISTENING",
    partNumber: 3,
    name: "Flyers Listening Part 3 — 3-Option MCQ",
    format: "PICTURE_DIALOGUE_MCQ",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "A2",
    optionCount: 3,
    candidateTask: "Listen and choose the correct picture (A, B, or C).",
    stimulusDescription: "Five questions with 3-picture strips. Dialogues require understanding contrast and correction.",
    distractorGuidance: "All three pictures are mentioned or suggested in the audio. Correct answer is confirmed positively; distractors are explicitly rejected.",
    languageConstraints: "Contrast markers: 'actually', 'instead', 'in the end'. Flyers vocabulary.",
  },
  {
    id: "FLYERS_L_PART4",
    exam: "FLYERS",
    skill: "LISTENING",
    partNumber: 4,
    name: "Flyers Listening Part 4 — Multiple Choice",
    format: "PICTURE_DIALOGUE_MCQ",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "A2",
    optionCount: 3,
    candidateTask: "Listen to the conversation. Tick (✓) the correct answer (A, B, or C).",
    stimulusDescription: "Monologue (radio programme, school announcement). Text-only MCQ questions (no pictures).",
    distractorGuidance: "Distractors are partially supported by audio. Correct answer requires integrating two pieces of information.",
    languageConstraints: "Inferencing from context. Connected speech features. Flyers vocabulary.",
  },
  {
    id: "FLYERS_L_PART5",
    exam: "FLYERS",
    skill: "LISTENING",
    partNumber: 5,
    name: "Flyers Listening Part 5 — Colour and Write",
    format: "COLOURING_WRITING",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "A2",
    candidateTask: "Listen and colour the correct part, then write the missing word.",
    stimulusDescription: "Detailed scene. Three items to colour; two words to write.",
    distractorGuidance: "Positions described using complex prepositional phrases. Writing item requires understanding of compound nouns or adjective–noun pairs.",
    languageConstraints: "Compound prepositions (next to, in the corner of). Flyers vocabulary.",
  },
  {
    id: "FLYERS_S_PART1",
    exam: "FLYERS",
    skill: "SPEAKING",
    partNumber: 1,
    name: "Flyers Speaking Part 1 — Story Sequencing",
    format: "STORY_SEQUENCING",
    itemCount: 4,
    marksPerItem: 2,
    cefr: "A2",
    candidateTask: "Put the four picture cards in order and tell a story about them.",
    stimulusDescription: "Four picture cards showing a narrative sequence. Candidate arranges them, then narrates.",
    distractorGuidance: "N/A — production. Mark scheme: logical sequence (1 pt) + narration quality (1 pt per picture).",
    languageConstraints: "Past tense narration. Linking adverbials (first, then, after that, finally). Flyers vocabulary.",
  },
  {
    id: "FLYERS_S_PART2",
    exam: "FLYERS",
    skill: "SPEAKING",
    partNumber: 2,
    name: "Flyers Speaking Part 2 — Personal Questions",
    format: "PERSONAL_QUESTIONS",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "A2",
    candidateTask: "Answer questions about yourself, your opinions, and your experiences.",
    stimulusDescription: "No visual. Examiner asks 5 questions including past-experience and opinion questions.",
    distractorGuidance: "N/A — production. Elicit extended responses (2–4 sentences).",
    languageConstraints: "Have you ever…? What did you…? What do you think about…? Would you like to…? Flyers vocabulary.",
  },

  // ── KET / A2 KEY ──────────────────────────────────────────────────────────
  {
    id: "KET_R_PART1",
    exam: "KET",
    skill: "READING",
    partNumber: 1,
    name: "KET Reading Part 1 — Matching (Notices & Signs)",
    format: "READING_MATCHING",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "A2",
    stimulusWordRange: [10, 30],
    optionCount: 8,
    candidateTask: "Read five short texts (notices, signs, messages). Match each to what it says (A–H).",
    stimulusDescription: "5 short authentic-style notices (shop signs, text messages, emails). 8 paraphrase options (3 distractors).",
    distractorGuidance: "Paraphrase options use different vocabulary for the same meaning. Distractors paraphrase related but not matching texts.",
    languageConstraints: "Short authentic text types: notices, SMS, short emails. A2 grammar and vocabulary. Idiomatic expressions common in notices.",
  },
  {
    id: "KET_R_PART2",
    exam: "KET",
    skill: "READING",
    partNumber: 2,
    name: "KET Reading Part 2 — Multiple Matching (People)",
    format: "READING_MATCHING",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "A2",
    stimulusWordRange: [150, 250],
    optionCount: 3,
    candidateTask: "Read descriptions of three people and eight short texts. Choose which text is suitable for which person.",
    stimulusDescription: "3 short profiles of people with needs/preferences + 8 short texts (hotel blurbs, event listings, etc.).",
    distractorGuidance: "Each profile matches only one text clearly. Other texts partially match but fail one criterion.",
    languageConstraints: "Functional language: needs, preferences, requirements. KET vocabulary. Scanning and matching skills.",
  },
  {
    id: "KET_R_PART3",
    exam: "KET",
    skill: "READING",
    partNumber: 3,
    name: "KET Reading Part 3 — Multiple Matching",
    format: "READING_MATCHING",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "A2",
    stimulusWordRange: [250, 350],
    optionCount: 8,
    candidateTask: "Read the text and choose the correct letter (A–H) to complete each sentence.",
    stimulusDescription: "Longer text (interview, article) with 5 sentence-completion questions using options A–H.",
    distractorGuidance: "Distractors are partially supported by the text but require misreading. Correct answers require full sentence comprehension.",
    languageConstraints: "KET vocabulary. Mix of literal retrieval and paraphrase recognition. No inference.",
  },
  {
    id: "KET_R_PART4",
    exam: "KET",
    skill: "READING",
    partNumber: 4,
    name: "KET Reading Part 4 — Gapped MCQ",
    format: "CLOZE_MCQ",
    itemCount: 7,
    marksPerItem: 1,
    cefr: "A2",
    stimulusWordRange: [100, 200],
    optionCount: 3,
    candidateTask: "Read the text. Choose the correct word (A, B, or C) for each gap.",
    stimulusDescription: "Short continuous text (informal article/story) with 7 gaps. Each gap offers 3 options.",
    distractorGuidance: "Mix of lexical and grammatical targets. Test collocations, phrasal verbs, and grammar (articles, tense, prepositions).",
    languageConstraints: "KET vocabulary. Present perfect, modal verbs, comparatives, passive voice at A2 level.",
  },
  {
    id: "KET_R_PART5",
    exam: "KET",
    skill: "READING",
    partNumber: 5,
    name: "KET Reading Part 5 — Open Cloze",
    format: "CLOZE_OPEN",
    itemCount: 6,
    marksPerItem: 1,
    cefr: "A2",
    stimulusWordRange: [80, 120],
    candidateTask: "Read the text. Fill in each gap with ONE word.",
    stimulusDescription: "Short text with 6 open gaps. No options provided.",
    distractorGuidance: "Each gap has one clearly correct answer (articles, prepositions, conjunctions, common verbs). Avoid gaps where two answers are possible.",
    languageConstraints: "Function words and high-frequency content words. KET grammar: articles, prepositions, auxiliaries, linkers.",
  },
  {
    id: "KET_R_PART6",
    exam: "KET",
    skill: "READING",
    partNumber: 6,
    name: "KET Reading Part 6 — Word Formation",
    format: "WORD_FORM",
    itemCount: 6,
    marksPerItem: 1,
    cefr: "A2",
    stimulusWordRange: [80, 120],
    candidateTask: "Read the text. Change the word in CAPITALS to fit the gap.",
    stimulusDescription: "Short text with 6 gaps. A base word in capitals is given; candidate produces the correct form.",
    distractorGuidance: "N/A — productive gap-fill. Test common derivations: -ful, -less, -ment, -tion, -er, -ly, un-, in-, mis-.",
    languageConstraints: "Common word families known at A2 level. No irregular derivations.",
  },
  {
    id: "KET_W_PART7",
    exam: "KET",
    skill: "WRITING",
    partNumber: 7,
    name: "KET Writing Part 7 — Email / Short Message",
    format: "SHORT_MESSAGE",
    itemCount: 1,
    marksPerItem: 5,
    cefr: "A2",
    outputWordTarget: [25, 35],
    candidateTask: "Write an email answering three bullet-point prompts in about 25–35 words.",
    stimulusDescription: "An email from a friend with a scenario. Three content points to address.",
    distractorGuidance: "N/A — productive. Mark scheme: Content (2 pt), Organisation (1 pt), Language accuracy (1 pt), Language range (1 pt).",
    languageConstraints: "Informal register. Three content points must be addressed. Acceptable range: 20–35 words.",
  },
  {
    id: "KET_L_PART1",
    exam: "KET",
    skill: "LISTENING",
    partNumber: 1,
    name: "KET Listening Part 1 — Picture MCQ",
    format: "PICTURE_DIALOGUE_MCQ",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "A2",
    optionCount: 3,
    candidateTask: "Listen. Which picture shows the answer? Choose A, B, or C.",
    stimulusDescription: "5 short dialogues. Each question has 3 pictures. Dialogues involve everyday situations.",
    distractorGuidance: "All three pictures mentioned or implied in audio. Correction and confirmation patterns present. Answer confirmed, distractors rejected.",
    languageConstraints: "Everyday situations: shopping, transport, weather, events. KET vocabulary. Natural spoken English with reductions.",
  },
  {
    id: "KET_L_PART2",
    exam: "KET",
    skill: "LISTENING",
    partNumber: 2,
    name: "KET Listening Part 2 — Gap Fill",
    format: "GAP_FILL_LISTEN",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "A2",
    candidateTask: "Listen to the monologue and complete the notes with 1–2 words.",
    stimulusDescription: "A monologue (~150 words: tour guide, shop announcement, recorded message) with a printed form/notes. 5 gaps.",
    distractorGuidance: "Each gap: one or two words only. No paraphrase required — exact or near-exact wording from audio expected.",
    languageConstraints: "Numbers, names, places, times, prices. KET vocabulary. Monologue pace and features.",
  },
  {
    id: "KET_L_PART3",
    exam: "KET",
    skill: "LISTENING",
    partNumber: 3,
    name: "KET Listening Part 3 — Matching",
    format: "MATCHING_LISTEN",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "A2",
    optionCount: 8,
    candidateTask: "Listen and write the letter (A–H) next to each name.",
    stimulusDescription: "A conversation in which 5 people are mentioned with their preferences. 8 options on the page (3 distractors).",
    distractorGuidance: "All 8 options mentioned or implied in conversation. Three distractors are explicitly mentioned but not chosen.",
    languageConstraints: "Likes/dislikes, plans, opinions. KET vocabulary. Natural dialogue with turn-taking.",
  },
  {
    id: "KET_L_PART4",
    exam: "KET",
    skill: "LISTENING",
    partNumber: 4,
    name: "KET Listening Part 4 — Short Dialogue MCQ",
    format: "PICTURE_DIALOGUE_MCQ",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "A2",
    optionCount: 3,
    candidateTask: "Listen to short conversations. Answer the multiple-choice question (A, B, or C).",
    stimulusDescription: "Five separate short dialogues. Text-based MCQ questions (no pictures).",
    distractorGuidance: "Distractors from same semantic domain as correct answer. Audio presents clear positive statement for the correct answer.",
    languageConstraints: "Comprehension of gist and detail. KET vocabulary. Natural connected speech.",
  },
  {
    id: "KET_L_PART5",
    exam: "KET",
    skill: "LISTENING",
    partNumber: 5,
    name: "KET Listening Part 5 — Gap Fill (Extended)",
    format: "GAP_FILL_LISTEN",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "A2",
    candidateTask: "Listen and complete the notes with 1–2 words or a number.",
    stimulusDescription: "A longer monologue (~200 words). A printed form or notes with 5 gaps.",
    distractorGuidance: "Audio provides information in different order to the printed form. Candidates must extract specific items.",
    languageConstraints: "Factual information: addresses, prices, opening times, descriptions. KET vocabulary.",
  },
  {
    id: "KET_S_PART1",
    exam: "KET",
    skill: "SPEAKING",
    partNumber: 1,
    name: "KET Speaking Part 1 — Personal Questions",
    format: "PERSONAL_QUESTIONS",
    itemCount: 6,
    marksPerItem: 2,
    cefr: "A2",
    candidateTask: "Answer the examiner's questions about everyday topics (family, school, hobbies, likes).",
    stimulusDescription: "No visual. Examiner asks 6 structured personal questions.",
    distractorGuidance: "N/A — production. Mark scheme: Grammar & vocabulary (5 pt), Interactive communication (5 pt), Pronunciation (5 pt).",
    languageConstraints: "Extended responses expected (3–5 sentences). Present simple, going to, past simple. KET vocabulary.",
  },
  {
    id: "KET_S_PART2",
    exam: "KET",
    skill: "SPEAKING",
    partNumber: 2,
    name: "KET Speaking Part 2 — Discuss a Photo",
    format: "DESCRIBE_PHOTO",
    itemCount: 1,
    marksPerItem: 5,
    cefr: "A2",
    candidateTask: "Talk about a photograph with the other candidate. Say what you can see and share your opinion.",
    stimulusDescription: "A colour photograph showing an everyday scene. Candidate must describe and comment.",
    distractorGuidance: "N/A — production. Assess: describes what is visible, speculates (maybe / I think), uses comparison.",
    languageConstraints: "There is/are. Present continuous for actions. Modal speculation (might, could). KET vocabulary.",
  },

  // ── PET / B1 PRELIMINARY ─────────────────────────────────────────────────
  {
    id: "PET_R_PART1",
    exam: "PET",
    skill: "READING",
    partNumber: 1,
    name: "PET Reading Part 1 — Short Text MCQ",
    format: "READING_MCQ",
    itemCount: 6,
    marksPerItem: 1,
    cefr: "B1",
    stimulusWordRange: [20, 50],
    optionCount: 3,
    candidateTask: "Read six short texts (notices, signs, emails). Choose the best answer (A, B, or C).",
    stimulusDescription: "Six short authentic-style texts. Questions test gist, purpose, and main message.",
    distractorGuidance: "One distractor captures literal meaning; one captures a related but incorrect meaning; correct answer captures communicative purpose.",
    languageConstraints: "Functional language: instructions, advice, offers, requests. PET vocabulary. Idiomatic usage in notices.",
  },
  {
    id: "PET_R_PART2",
    exam: "PET",
    skill: "READING",
    partNumber: 2,
    name: "PET Reading Part 2 — Multiple Matching",
    format: "READING_MATCHING",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "B1",
    stimulusWordRange: [300, 450],
    optionCount: 5,
    candidateTask: "Read the descriptions and short texts. Match each person to the correct text.",
    stimulusDescription: "Five profiles of people + five short descriptive texts. Each person matches one text.",
    distractorGuidance: "Profiles and texts have overlapping vocabulary. Correct match requires integrating multiple criteria simultaneously.",
    languageConstraints: "B1 vocabulary and grammar. Scanning and matching. Complex sentence structures.",
  },
  {
    id: "PET_R_PART3",
    exam: "PET",
    skill: "READING",
    partNumber: 3,
    name: "PET Reading Part 3 — Long Text MCQ",
    format: "READING_MCQ",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "B1",
    stimulusWordRange: [350, 500],
    optionCount: 4,
    candidateTask: "Read the text. Answer five four-option multiple-choice questions.",
    stimulusDescription: "Factual or narrative text (~450 words). Questions assess detailed understanding, inference, and attitude.",
    distractorGuidance: "All four options plausible. One distractor misreads tone/attitude; one uses information from wrong paragraph; one paraphrases incorrectly.",
    languageConstraints: "B1 vocabulary. Mix of literal, inferential, and evaluative questions. Author's purpose questions included.",
  },
  {
    id: "PET_R_PART4",
    exam: "PET",
    skill: "READING",
    partNumber: 4,
    name: "PET Reading Part 4 — Gapped Text (Sentences)",
    format: "READING_GAPPED_TEXT",
    itemCount: 5,
    marksPerItem: 1,
    cefr: "B1",
    stimulusWordRange: [300, 450],
    optionCount: 8,
    candidateTask: "Five sentences have been removed from a text. Choose from sentences A–H where each one fits.",
    stimulusDescription: "A longer text with 5 sentence-level gaps. 8 candidate sentences provided (3 distractors).",
    distractorGuidance: "Distractors must fit grammatically but are semantically or logically wrong. Test discourse structure, referencing, and text cohesion.",
    languageConstraints: "Cohesive devices (however, therefore, as a result). Pronoun reference and lexical cohesion. B1 vocabulary.",
  },
  {
    id: "PET_R_PART5",
    exam: "PET",
    skill: "READING",
    partNumber: 5,
    name: "PET Reading Part 5 — Multiple-Choice Cloze",
    format: "CLOZE_MCQ",
    itemCount: 6,
    marksPerItem: 1,
    cefr: "B1",
    stimulusWordRange: [100, 150],
    optionCount: 4,
    candidateTask: "Read the text. Choose the correct word (A, B, C, or D) for each gap.",
    stimulusDescription: "Short text with 6 four-option lexical or grammatical gaps.",
    distractorGuidance: "Test collocations, phrasal verbs, idiomatic expressions, and verb patterns. All four options same word class. Three distractors in same semantic field.",
    languageConstraints: "PET vocabulary including idioms, phrasal verbs, and collocations. Complex grammar: conditionals, reported speech, passive.",
  },
  {
    id: "PET_W_PART1",
    exam: "PET",
    skill: "WRITING",
    partNumber: 1,
    name: "PET Writing Part 1 — Email",
    format: "SHORT_MESSAGE",
    itemCount: 1,
    marksPerItem: 10,
    cefr: "B1",
    outputWordTarget: [80, 100],
    candidateTask: "Read an email from a friend. Write a reply addressing all three content points in 80–100 words.",
    stimulusDescription: "An informal email with three bullet-point prompts to address (e.g., describe, explain, suggest).",
    distractorGuidance: "N/A — production. Mark scheme: Content (4 pt — 1 per prompt + overall), Communication (2 pt), Organisation (2 pt), Language (2 pt).",
    languageConstraints: "Informal register. Three content points required. Appropriate opening and closing. PET vocabulary and grammar.",
  },
  {
    id: "PET_W_PART2",
    exam: "PET",
    skill: "WRITING",
    partNumber: 2,
    name: "PET Writing Part 2 — Article or Story",
    format: "ARTICLE_OR_STORY",
    itemCount: 1,
    marksPerItem: 10,
    cefr: "B1",
    outputWordTarget: [80, 100],
    candidateTask: "Write an article OR a story (choice). Must be clearly structured, engaging, and approximately 100 words.",
    stimulusDescription: "Choice of two tasks: (A) Article with a given title and audience, or (B) story starting with a given sentence.",
    distractorGuidance: "N/A — production. Mark scheme assesses: content, communicative achievement, organisation, language range and accuracy.",
    languageConstraints: "B1 grammar and vocabulary range. Article: clear paragraphs, engaging introduction. Story: narrative tense, sequencing adverbs.",
  },
  {
    id: "PET_L_PART1",
    exam: "PET",
    skill: "LISTENING",
    partNumber: 1,
    name: "PET Listening Part 1 — Picture MCQ",
    format: "PICTURE_DIALOGUE_MCQ",
    itemCount: 7,
    marksPerItem: 1,
    cefr: "B1",
    optionCount: 3,
    candidateTask: "Listen. Look at the three pictures. Choose the best answer (A, B, or C).",
    stimulusDescription: "Seven short dialogues. Each followed by a picture-MCQ question.",
    distractorGuidance: "Correct answer requires integrating information across the full dialogue, not just the final sentence. Distractors are plausible from partial listening.",
    languageConstraints: "Everyday B1 topics: transport, shopping, events, relationships. PET vocabulary. Natural speech rate (~130 wpm).",
  },
  {
    id: "PET_L_PART2",
    exam: "PET",
    skill: "LISTENING",
    partNumber: 2,
    name: "PET Listening Part 2 — Gap Fill",
    format: "GAP_FILL_LISTEN",
    itemCount: 6,
    marksPerItem: 1,
    cefr: "B1",
    candidateTask: "Listen to the monologue. Complete the notes with 1–3 words or a number.",
    stimulusDescription: "Monologue (~200 words: radio broadcast, informational talk). Printed notes with 6 gaps.",
    distractorGuidance: "Audio gives information in same order as form. Self-correction present in at least 2 items. Answers 1–3 words, often specific factual data.",
    languageConstraints: "Specific vocabulary: numbers, dates, proper nouns, compound nouns. B1 monologue features (hedging, repetition).",
  },
  {
    id: "PET_L_PART3",
    exam: "PET",
    skill: "LISTENING",
    partNumber: 3,
    name: "PET Listening Part 3 — Matching",
    format: "MATCHING_LISTEN",
    itemCount: 6,
    marksPerItem: 1,
    cefr: "B1",
    optionCount: 8,
    candidateTask: "You will hear six people speaking. Match each speaker to the reason they give (A–H).",
    stimulusDescription: "Six short monologues from different speakers on the same theme. 8 options (2 distractors).",
    distractorGuidance: "Each speaker clearly supports one option. Distractors are thematically close but logically ruled out by the audio.",
    languageConstraints: "Personal opinions, reasons, recommendations. B1 vocabulary. Speaker stance and attitude.",
  },
  {
    id: "PET_L_PART4",
    exam: "PET",
    skill: "LISTENING",
    partNumber: 4,
    name: "PET Listening Part 4 — Long Text MCQ",
    format: "PICTURE_DIALOGUE_MCQ",
    itemCount: 6,
    marksPerItem: 1,
    cefr: "B1",
    optionCount: 3,
    candidateTask: "Listen to an interview or conversation. Answer MCQ questions (A, B, or C).",
    stimulusDescription: "A longer interview or discussion (~300 words). 6 detailed-comprehension MCQ questions.",
    distractorGuidance: "Questions test attitude, opinion, inference, and detail. At least 2 questions require inferencing beyond literal content.",
    languageConstraints: "B1 vocabulary. Attitudes and opinions expressed indirectly. Discourse markers: 'well', 'I mean', 'actually'.",
  },
  {
    id: "PET_S_PART1",
    exam: "PET",
    skill: "SPEAKING",
    partNumber: 1,
    name: "PET Speaking Part 1 — Introduction",
    format: "PERSONAL_QUESTIONS",
    itemCount: 4,
    marksPerItem: 2,
    cefr: "B1",
    candidateTask: "Introduce yourself and answer questions about your life, studies, experiences, and plans.",
    stimulusDescription: "No visual. Examiner asks structured questions.",
    distractorGuidance: "N/A — production. Assess: Grammar & Vocabulary, Discourse Management, Pronunciation, Interactive Communication.",
    languageConstraints: "Present perfect for experience, going to / will for future. Extended responses (4–6 sentences). PET vocabulary.",
  },
  {
    id: "PET_S_PART2",
    exam: "PET",
    skill: "SPEAKING",
    partNumber: 2,
    name: "PET Speaking Part 2 — Collaborative Task",
    format: "COLLABORATIVE_TASK",
    itemCount: 1,
    marksPerItem: 10,
    cefr: "B1",
    candidateTask: "Discuss a scenario with the other candidate. Agree on a decision together (2–3 minutes).",
    stimulusDescription: "A visual prompt showing a scenario (e.g., choosing activities for a school trip). Candidates must discuss options and reach agreement.",
    distractorGuidance: "N/A — interaction. Assess: ability to initiate, agree/disagree politely, reach a decision cooperatively.",
    languageConstraints: "Functional language: suggestions (What about…?), agreement (I think that's a good idea), disagreement (I'm not sure about…), justification. PET vocabulary.",
  },
  {
    id: "PET_S_PART3",
    exam: "PET",
    skill: "SPEAKING",
    partNumber: 3,
    name: "PET Speaking Part 3 — Long Turn (Photo Description)",
    format: "DESCRIBE_PHOTO",
    itemCount: 1,
    marksPerItem: 5,
    cefr: "B1",
    candidateTask: "Talk alone about a photograph for approximately one minute.",
    stimulusDescription: "A colour photograph of a scene (people in a location doing an activity).",
    distractorGuidance: "N/A — production. Assess extended monologue: description → speculation → personal connection.",
    languageConstraints: "Present simple / continuous for description. Modal speculation (might/could/must). Discourse management: 'In the foreground… In the background…' PET vocabulary.",
  },
  {
    id: "PET_S_PART4",
    exam: "PET",
    skill: "SPEAKING",
    partNumber: 4,
    name: "PET Speaking Part 4 — Discussion",
    format: "PERSONAL_QUESTIONS",
    itemCount: 1,
    marksPerItem: 5,
    cefr: "B1",
    candidateTask: "Discuss the topic from Part 3 with the other candidate. Express opinions and ask questions.",
    stimulusDescription: "No new visual. Discussion based on Part 3 theme (e.g., 'Do you enjoy going to parks?').",
    distractorGuidance: "N/A — interaction. Assess: opinion expression, asking follow-up questions, maintaining discussion.",
    languageConstraints: "Opinion language: I believe, In my opinion, It seems to me. Agreeing/disagreeing. PET vocabulary.",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// 4. EXAM-LEVEL METADATA
// ─────────────────────────────────────────────────────────────────────────────

export interface CambridgeExamMeta {
  exam: CambridgeExam;
  fullName: string;
  shortName: string;
  cefr: CefrLevel;
  thetaRange: [number, number];
  ageGroup: string;
  totalMarks: number;
  passMarkPercent: number;
  /** Cambridge Scale Score (CSS) range */
  cssRange: [number, number];
  skills: CambridgeSkill[];
  vocabularySize: number;
  /** Official Cambridge word list URL (for reference) */
  wordListReference: string;
  topicAreas: string[];
  grammarSyllabus: string[];
  functionsSyllabus: string[];
}

export const CAMBRIDGE_EXAM_META: Record<CambridgeExam, CambridgeExamMeta> = {
  STARTERS: {
    exam: "STARTERS",
    fullName: "Cambridge Young Learners English — Starters",
    shortName: "Starters",
    cefr: "PRE_A1",
    thetaRange: [-4.0, -2.5],
    ageGroup: "7–8 years",
    totalMarks: 50,
    passMarkPercent: 60,
    cssRange: [0, 5],
    skills: ["READING_WRITING", "LISTENING", "SPEAKING"],
    vocabularySize: 150,
    wordListReference: "https://www.cambridgeenglish.org/Images/young-learners-word-list-starters.pdf",
    topicAreas: [
      "animals",
      "classroom objects",
      "colours",
      "family",
      "food and drink",
      "home",
      "numbers (1–20)",
      "sport and leisure",
      "toys",
      "transport",
      "weather",
    ],
    grammarSyllabus: [
      "Simple present (to be, have, like, want)",
      "Imperatives",
      "Demonstratives (this, that, these, those)",
      "Articles (a, an, the)",
      "Possessive adjectives (my, your, his, her)",
      "Plurals (regular)",
      "Question words (what, where, who, how many)",
      "There is / there are",
      "Can (ability)",
      "Simple present (other verbs): I play, she plays",
    ],
    functionsSyllabus: [
      "Identifying objects",
      "Expressing likes/dislikes",
      "Describing location (on, in, under, next to)",
      "Counting and identifying quantities",
      "Naming colours and describing appearance",
      "Greetings and introductions",
    ],
  },

  MOVERS: {
    exam: "MOVERS",
    fullName: "Cambridge Young Learners English — Movers",
    shortName: "Movers",
    cefr: "A1",
    thetaRange: [-2.5, -1.5],
    ageGroup: "8–11 years",
    totalMarks: 60,
    passMarkPercent: 60,
    cssRange: [0, 5],
    skills: ["READING_WRITING", "LISTENING", "SPEAKING"],
    vocabularySize: 300,
    wordListReference: "https://www.cambridgeenglish.org/Images/young-learners-word-list-movers.pdf",
    topicAreas: [
      "animals (extended)",
      "body and health",
      "clothes",
      "daily routines",
      "environment",
      "feelings and emotions",
      "food and drink (extended)",
      "free time and hobbies",
      "home (extended)",
      "numbers (1–100)",
      "places in town",
      "school",
      "sport (extended)",
      "time",
      "transport (extended)",
    ],
    grammarSyllabus: [
      "Simple past (regular and common irregular)",
      "Present continuous",
      "Going to (future plans)",
      "Comparative and superlative adjectives",
      "Object pronouns (me, him, her, us, them)",
      "Some / any / no",
      "How much / how many",
      "Prepositions of time (at, on, in)",
      "Prepositions of place (extended)",
      "Would like",
      "Could (polite requests)",
      "Because (reason clauses)",
    ],
    functionsSyllabus: [
      "Describing past events",
      "Describing ongoing actions",
      "Expressing future plans",
      "Comparing things",
      "Expressing preferences",
      "Giving reasons",
      "Describing people's appearance",
      "Talking about feelings",
    ],
  },

  FLYERS: {
    exam: "FLYERS",
    fullName: "Cambridge Young Learners English — Flyers",
    shortName: "Flyers",
    cefr: "A2",
    thetaRange: [-1.75, -0.75],
    ageGroup: "9–12 years",
    totalMarks: 75,
    passMarkPercent: 60,
    cssRange: [0, 5],
    skills: ["READING_WRITING", "LISTENING", "SPEAKING"],
    vocabularySize: 500,
    wordListReference: "https://www.cambridgeenglish.org/Images/young-learners-word-list-flyers.pdf",
    topicAreas: [
      "the environment",
      "science and technology",
      "travel and holidays",
      "the world around us",
      "people and relationships",
      "arts and entertainment",
      "health and body",
      "food and cooking",
      "school and education",
      "jobs and work",
      "sport and fitness",
      "shopping",
      "news and current events (simplified)",
    ],
    grammarSyllabus: [
      "Present perfect (experience and recent events)",
      "Past continuous",
      "First conditional",
      "Relative clauses (who, which, that)",
      "Reported speech (said, told)",
      "Passive voice (simple present and past)",
      "Much, many, a lot of, a few, a little",
      "Modal verbs (should, must, might, could)",
      "Question tags",
      "Adverbs of manner and degree",
    ],
    functionsSyllabus: [
      "Narrating stories",
      "Describing and comparing",
      "Expressing opinions and preferences",
      "Speculating and predicting",
      "Giving advice",
      "Reporting information",
      "Describing processes",
    ],
  },

  KET: {
    exam: "KET",
    fullName: "Cambridge A2 Key (formerly Key English Test)",
    shortName: "A2 Key",
    cefr: "A2",
    thetaRange: [-1.75, -0.5],
    ageGroup: "Any (typically 14+)",
    totalMarks: 70,
    passMarkPercent: 65,
    cssRange: [100, 150],
    skills: ["READING", "WRITING", "LISTENING", "SPEAKING"],
    vocabularySize: 1500,
    wordListReference: "https://www.cambridgeenglish.org/Images/a2-key-vocabulary-list.pdf",
    topicAreas: [
      "clothes and accessories",
      "education",
      "entertainment and media",
      "environment",
      "family and relationships",
      "food and drink",
      "free time and hobbies",
      "health and medicine",
      "house and home",
      "language",
      "personal feelings, opinions, experiences",
      "places and buildings",
      "services (post, bank, police)",
      "shopping",
      "sport",
      "the natural world",
      "transport",
      "travel and holidays",
      "work and jobs",
    ],
    grammarSyllabus: [
      "All tenses through present perfect",
      "Modal verbs (can, could, will, would, should, may, might, must)",
      "First and second conditional",
      "Comparative and superlative (regular and irregular)",
      "Passive (simple present, simple past)",
      "Infinitive and gerund after common verbs",
      "Relative clauses (who, which, that, where)",
      "Question formation (all types)",
      "Reported speech (statements and questions)",
      "Prepositions (time, place, manner)",
    ],
    functionsSyllabus: [
      "Making and responding to requests",
      "Giving advice and making suggestions",
      "Expressing agreement and disagreement",
      "Describing people, places, and objects",
      "Expressing ability and possibility",
      "Asking for and giving information",
      "Expressing likes, dislikes, and preferences",
      "Making arrangements",
      "Complaining and apologising",
    ],
  },

  PET: {
    exam: "PET",
    fullName: "Cambridge B1 Preliminary (formerly Preliminary English Test)",
    shortName: "B1 Preliminary",
    cefr: "B1",
    thetaRange: [-0.5, 0.75],
    ageGroup: "Any (typically 16+)",
    totalMarks: 80,
    passMarkPercent: 70,
    cssRange: [120, 170],
    skills: ["READING", "WRITING", "LISTENING", "SPEAKING"],
    vocabularySize: 3500,
    wordListReference: "https://www.cambridgeenglish.org/Images/b1-preliminary-vocabulary-list.pdf",
    topicAreas: [
      "arts and media",
      "climate and environment",
      "education and study",
      "entertainment",
      "food and drink",
      "health and fitness",
      "hobbies and leisure",
      "house and home",
      "language and communication",
      "people and society",
      "personal feelings and opinions",
      "places and geography",
      "science and technology",
      "shopping and services",
      "sport",
      "transport and travel",
      "work and employment",
      "the natural world",
    ],
    grammarSyllabus: [
      "All tenses through past perfect",
      "Modal verbs (all forms, including perfect modals: should have, could have)",
      "Conditionals (zero, first, second, third)",
      "Passive (all simple tenses)",
      "Reported speech (statements, questions, commands)",
      "Infinitive, gerund, and bare infinitive structures",
      "Defining and non-defining relative clauses",
      "Sentence patterns: suggest, recommend, advise + gerund",
      "Conjunctions and discourse markers (however, although, despite, in spite of)",
      "Phrasal verbs (common B1 verbs)",
      "Comparative structures (as…as, not as…as, twice as…as)",
    ],
    functionsSyllabus: [
      "Giving opinions and justifying them",
      "Expressing certainty, possibility, and doubt",
      "Narrating and describing events in the past",
      "Making suggestions and recommendations",
      "Discussing advantages and disadvantages",
      "Expressing sympathy and concern",
      "Describing changes and processes",
      "Writing formal and informal messages",
      "Discussing plans and ambitions",
    ],
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// 5. LOOK-UP HELPERS
// ─────────────────────────────────────────────────────────────────────────────

/** Get all tasks for a specific exam */
export function getTasksForExam(exam: CambridgeExam): CambridgeTask[] {
  return CAMBRIDGE_TASKS.filter((t) => t.exam === exam);
}

/** Get all tasks for a specific exam + skill */
export function getTasksForSkill(
  exam: CambridgeExam,
  skill: CambridgeSkill
): CambridgeTask[] {
  return CAMBRIDGE_TASKS.filter((t) => t.exam === exam && t.skill === skill);
}

/** Get task by its ID */
export function getTask(taskId: string): CambridgeTask | undefined {
  return CAMBRIDGE_TASKS.find((t) => t.id === taskId);
}

/** Map a Cambridge exam to its CEFR level */
export function examToCefr(exam: CambridgeExam): CefrLevel {
  return CAMBRIDGE_EXAM_META[exam].cefr;
}

/** Map a CEFR level to the relevant Cambridge exam(s) */
export function cefrToExams(cefr: CefrLevel): CambridgeExam[] {
  return Object.values(CAMBRIDGE_EXAM_META)
    .filter((m) => m.cefr === cefr)
    .map((m) => m.exam);
}

/** Get vocabulary topic list for an exam */
export function getTopicAreas(exam: CambridgeExam): string[] {
  return CAMBRIDGE_EXAM_META[exam].topicAreas;
}

/** Get grammar syllabus for an exam */
export function getGrammarSyllabus(exam: CambridgeExam): string[] {
  return CAMBRIDGE_EXAM_META[exam].grammarSyllabus;
}
