/** Answer key supplied by the user, aligned to student PDF questions 1–96. */
export const OZGUN_ANSWER_KEY = "BDACACDBCABDBDCADBACCADBDACBBDACACDBCBADADBCDCBABCADDBCACADBADBCDCABBACDCADBADBCDBCABCADCDBAABDC";
